# Generated by Django 3.0.7 on 2024-08-11 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sender', '0002_auto_20240807_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default=895427, max_length=6),
        ),
    ]
