# Generated by Django 3.0.7 on 2024-08-11 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sender', '0003_auto_20240811_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default=626181, max_length=6),
        ),
    ]
